# Open AI - Parallel Runnables

# Langchain imports
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate 
from langchain_core.output_parsers import StrOutputParser

# Langchain Runnables imports
from langchain_core.runnables import RunnableSequence, RunnableParallel

# load environment variables from .env file
from dotenv import load_dotenv  

load_dotenv()

# Create Prompt 1 
prompt1 = PromptTemplate(
    template = 'Generate a tweet about {topic}',
    input_variables = ['topic']
)

# Create Prompt 2
prompt2 = PromptTemplate(
    template = 'Generate a Linkedin post about {topic}',
    input_variables = ['topic']
)

# Create OpenAI Model 
model = ChatOpenAI()

# Create Output Parser 
parser = StrOutputParser()

# Create Runnable Sequence for Prompt 1
tweet_chain1 = RunnableSequence(
    prompt1,
    model,
    parser
)

# Create Runnable Sequence for Prompt 2
linkedin_chain2 = RunnableSequence(
    prompt2,
    model,
    parser  
)   


# Create a parallel runnable that runs both sequences in parallel
parallel_chain = RunnableParallel({
    'tweet': tweet_chain1,
    'linkedin': linkedin_chain2
})


# Invoke the parallel chain with a topic 
result = parallel_chain.invoke({'topic':'AI'})


# Print the result of the tweet 
print(result['tweet'])

# Print the result of the linkedin post
print(result['linkedin'])



# Example of the tweet and linkdin post generated by the parallel chain


        #             Input
        #           topic = AI
        #               |
        #      ┌────────┴────────┐
        #      ↓                 ↓
        # Tweet Chain       LinkedIn Chain
        #      ↓                 ↓
        #   Tweet            LinkedIn Post




# RunnableParallel allows you to run multiple RunnableSequences in parallel, which can be useful for generating multiple outputs from the same input. In this example, we created two RunnableSequences: one for generating a tweet and another for generating a LinkedIn post about the same topic. The RunnableParallel takes a dictionary of RunnableSequences and runs them in parallel, returning a dictionary of results.